{% set version = "0.3.2" %}

package:
  name: hatch-nodejs-version
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hatch-nodejs-version/hatch_nodejs_version-{{ version }}.tar.gz
  sha256: 8a7828d817b71e50bbbbb01c9bfc0b329657b7900c56846489b9c958de15b54c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - hatchling >=0.21.0
    - python >=3.7

test:
  source_files:
    - tests
  requires:
    - m2-grep  # [win]
    - pip
    - pytest >=7.0.1
    - pytest-cov
  imports:
    - hatch_nodejs_version
  commands:
    - pip check
    - pip list
    - pip list | grep -iE 'hatch-nodejs-version\s*{{ version.replace('.', '\.') }}'
    - pytest -vvv --capture=tee-sys --cov=hatch_nodejs_version --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80

about:
  home: https://github.com/agoose77/hatch-nodejs-version
  summary: Hatch plugin for versioning from a package.json file
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
    - agoose77
    - thewchan
